### ISSUE TITLE
Exception in thread "main"

### ISSUE THREAD

**Issue by dexterPankiji** [cantryDev/CSGOCaseStatsViewerV2#25]
Exception in thread "main" de.cantry.csgocasestatsviewerv2.exception.GlobalException: Failed to retrieve all needed account information. Cookies invalid?
        at de.cantry.csgocasestatsviewerv2.steam.service.DumpService.requireCookies(DumpService.java:234)
        at de.cantry.csgocasestatsviewerv2.steam.service.DumpService.dump(DumpService.java:49)
        at de.cantry.csgocasestatsviewerv2.Main.main(Main.java:56)
Caused by: java.lang.Exception: RegexFindFirst, pattern not found. Searched: href="(https://steamcommunity.com/[^/]+/[^/]+/inventory/)"
        at de.cantry.csgocasestatsviewerv2.util.RegexUtils.regexFindFirst(RegexUtils.java:16)
        at de.cantry.csgocasestatsviewerv2.steam.service.DumpService.requireCookies(DumpService.java:228)
        ... 2 more

**Comment by z1mplethechicken** [comment]
this was the same for me, any fixes?

**Comment by cantryDev** [comment]
Seems like the cookies you pasted are incorrect.
Make sure you are logged in and follow the instructions

**Comment by dexterPankiji** [comment]
No, i did everything like told in the instructions...it also worked like 1 year ago in CS:GO...

**Comment by Kjerne** [comment]
> No, i did everything like told in the instructions...it also worked like 1 year ago in CS:GO...

Did you find a fix? i have same issue

**Comment by Patacka** [comment]
You have to be on your Profile and grab the cookie there.
